# Site settings
title: Chris Gullickson's Software Development Blog
header-img: img/home-bg.png
email: cgullickson5@gmail.com
copyright_name: cgullickson
description: > # this means to ignore newlines until "baseurl:"
  Learning to Program One Day at a Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cgullickson
learn_profile: cgullickson
email_username: cgullickson5@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
